oddam_w_dobre_rece/oddam_w_dobre_rece/urls.py
from django.contrib import admin
from django.urls import path

from charity.views import LandingPageView, AddDonationView, LoginView, RegisterView, LogoutView, ConfirmationView, \
    UserProfileView

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', LandingPageView.as_view(), name="index"),
    path('add-donation/', AddDonationView.as_view(), name="add-donation"),
    path('login/', LoginView.as_view(), name="login"),
    path('register/', RegisterView.as_view(), name="register"),
    path('logout/', LogoutView.as_view(), name="logout"),
    path('confirmation', ConfirmationView.as_view(), name="confirmation"),
    path('profile/', UserProfileView.as_view(), name='user-profile'),
]

oddam_w_dobre_rece/charity/models.py
from django.contrib.auth.models import AbstractUser
from django.db import models
from django.utils.translation import gettext_lazy as _

from .managers import UserManager

INSTITUTION_TYPES = [
    ('FU', 'Fundacja'),
    ('OP', 'Organizacja pozarządowa'),
    ('ZO', 'Zbiórka lokalna'),
]


class CustomUser(AbstractUser):
    username = None
    email = models.EmailField(_("email address"), unique=True)

    USERNAME_FIELD = 'email'
    REQUIRED_FIELDS = []

    objects = UserManager()

    def __str__(self):
        return self.email


class Category(models.Model):
    name = models.CharField(max_length=128)

    def __str__(self):
        return self.name


class Institution(models.Model):
    name = models.CharField(max_length=128)
    description = models.TextField()
    type = models.CharField(max_length=2, choices=INSTITUTION_TYPES, default='FU')
    categories = models.ManyToManyField(Category)

    def __str__(self):
        return self.name


class Donation(models.Model):
    quantity = models.IntegerField()
    categories = models.ManyToManyField(Category)
    institution = models.ForeignKey(Institution, on_delete=models.CASCADE)
    address = models.CharField(max_length=128)
    phone_number = models.IntegerField()
    city = models.CharField(max_length=64)
    zip_code = models.CharField(max_length=16)
    pick_up_date = models.DateField()
    pick_up_time = models.DateTimeField()
    pick_up_comment = models.TextField()
    user = models.ForeignKey(CustomUser, on_delete=models.CASCADE, null=True, default=None)
    

oddam_w_dobre_rece/charity/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm

from .models import CustomUser, Donation


class SignUpForm(UserCreationForm):
    class Meta:
        model = CustomUser
        fields = ('email', 'first_name', 'last_name', 'password1', 'password2')

    def __init__(self, *args, **kwargs):
        super(SignUpForm, self).__init__(*args, **kwargs)
        self.fields['first_name'].widget.attrs.update({'placeholder': ('Imię')})
        self.fields['last_name'].widget.attrs.update({'placeholder': ('Nazwisko')})
        self.fields['email'].widget.attrs.update({'placeholder': ('Email')})
        self.fields['password1'].widget.attrs.update({'placeholder': ('Hasło')})
        self.fields['password2'].widget.attrs.update({'placeholder': ('Powtórz hasło')})


class LoginForm(forms.Form):
    username = forms.CharField(max_length=254, label="Login",
                               widget=forms.TextInput(attrs={'placeholder': 'Login'}))
    password = forms.CharField(widget=forms.PasswordInput(attrs={'placeholder': 'Hasło'}))


class AddDonationForm(forms.ModelForm):
    class Meta:
        model = Donation
        fields = ['quantity', 'categories', 'institution', 'address', 'phone_number', 'city',
                  'zip_code', 'pick_up_date', 'pick_up_time', 'pick_up_comment']

oddam_w_dobre_rece/charity/views.py
import datetime

from django.contrib.auth import authenticate, login, logout
from django.contrib.auth.models import User
from django.shortcuts import render, redirect
from django.urls import reverse
from django.views import View

from .forms import SignUpForm, LoginForm, AddDonationForm
from .models import Institution, Donation, Category


class LandingPageView(View):
    def get(self, request):
        institutions = Institution.objects.all()
        institutions_count = institutions.count()
        donations = Donation.objects.all()
        categories = Category.objects.all()
        # quantity = []
        # for donation in donations:
        #     quantity.append(donation.quantity)
        sum_of_bags = sum([donation.quantity for donation in donations])
        ctx = {
            "institutions": institutions,
            "institutions_count": institutions_count,
            "sum_of_bags": sum_of_bags,
            "categories": categories,
        }
        return render(request, "index.html", context=ctx)


class AddDonationView(View):
    def get(self, request):
        if not request.user.is_authenticated:
            return redirect('/login/#login-section/')
        categories = Category.objects.all()
        institutions = Institution.objects.all()
        form = AddDonationForm()
        ctx = {
            'categories': categories,
            'institutions': institutions,
            'form': form
        }
        return render(request, "form.html", ctx)

    def post(self, request):
        categories = request.POST.get('chosen-categories')
        bags = int(request.POST.get('bags'))
        institution = Institution.objects.get(pk=request.POST.get('organization'))
        address = request.POST.get('address')
        city = request.POST.get('city')
        zip_code = request.POST.get('postcode')
        phone_number = request.POST.get('phone')
        pick_up_date = datetime.datetime.strptime(request.POST.get('data'), "%Y-%m-%d").date()
        pick_up_time = datetime.datetime.strptime(request.POST.get('time'), "%H:%M").time()
        pick_up_comment = request.POST.get('more_info')
        user = request.user

        donation = Donation.objects.create(quantity=bags, institution=institution, address=address,
                                           city=city, zip_code=zip_code, phone_number=phone_number,
                                           pick_up_date=pick_up_date, pick_up_time=pick_up_time,
                                           pick_up_comment=pick_up_comment, user=user
                                           )
        for category in categories.split(','):
            category_object = Category.objects.get(pk=category)
            donation.categories.add(category_object)

        return redirect('/confirmation/')


class ConfirmationView(View):
    def get(self, request):
        return render(request, 'form-confirmation.html')


class RegisterView(View):
    def get(self, request):
        form = SignUpForm()
        return render(request, 'register.html', {'form': form})

    def post(self, request):
        form = SignUpForm(request.POST)
        if form.is_valid():
            form.save()
            return redirect('/login/#login-section')
        return render(request, 'register.html', {'form': form})


class LoginView(View):
    def get(self, request):
        form = LoginForm()
        return render(request, 'login.html', {'form': form})

    def post(self, request):
        form = LoginForm(request.POST)

        if form.is_valid():
            username = form.cleaned_data['username']
            password = form.cleaned_data['password']

            user = authenticate(username=username, password=password)
            if user is not None:
                login(request, user)
                return redirect(reverse('index'))
            user = User.objects.filter(username=username)
            if user:
                error = 'Nieprawidłowe hasło'
                form = LoginForm()
                ctx = {'form': form, 'error': error}
                return render(request, 'login.html', ctx)
            return redirect('/register/#register-section')

        else:
            ctx = {'form': form}
            return render(request, 'login.html', ctx)


class LogoutView(View):
    def get(self, request):
        logout(request)
        return redirect("index")


class UserProfileView(View):
    def get(self, request):
        return render(request, "user-profile.html")

oddam_w_dobre_rece/charity/templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="pl">
  <head>
    <meta charset="UTF-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <meta http-equiv="X-UA-Compatible" content="ie=edge" />
    <title>Document</title>
    <link rel="stylesheet" href="{% static "css/style.css" %}" />
  </head>
  <body>
    <header class="header--main-page">
      <nav class="container container--70">
        <ul class="nav--actions">
          {% if user.is_authenticated %}
            <li class="logged-user">
              Witaj {{ user.first_name }}
              <ul class="dropdown">
                <li><a href="/profile#user-profile">Profil</a></li>
                <li><a href="#">Ustawienia</a></li>
                {% if user.is_superuser %}
                <li><a href="/admin">Panel administratora</a></li>
                {% endif %}
                <li><a href="/logout">Wyloguj</a></li>
              </ul>
            </li>
          {% else %}
            <li><a href="/login/#login-section" class="btn btn--small btn--without-border">Zaloguj</a></li>
            <li><a href="/register/#register-section" class="btn btn--small btn--highlighted">Załóż konto</a></li>
          {% endif %}
        </ul>

        <ul>
          <li><a href="/" class="btn btn--without-border active">Start</a></li>
          <li><a href="#steps" class="btn btn--without-border">O co chodzi?</a></li>
          <li><a href="#about-us" class="btn btn--without-border">O nas</a></li>
          <li><a href="#help" class="btn btn--without-border">Fundacje i organizacje</a></li>
          <li><a href="/add-donation/#form-steps" class="btn btn--without-border">Przekaż dary</a></li>
          <li><a href="#contact" class="btn btn--without-border">Kontakt</a></li>
        </ul>
      </nav>
      <div class="slogan container container--90">
        <div class="slogan--item">
          <h1>
            Zacznij pomagać!<br />
            Oddaj niechciane rzeczy w zaufane ręce
          </h1>
        </div>
      </div>

    </header>

{% block content %}

{% endblock content %}

  <footer>
        <div id="contact" class="contact">
          <h2>Skontaktuj się z nami</h2>
          <h3>Formularz kontaktowy</h3>
          <form class="form--contact">
            <div class="form-group form-group--50"><input type="text" name="name" placeholder="Imię" /></div>
            <div class="form-group form-group--50"><input type="text" name="surname" placeholder="Nazwisko" /></div>

            <div class="form-group"><textarea name="message" placeholder="Wiadomość" rows="1"></textarea></div>

            <button class="btn" type="submit">Wyślij</button>
          </form>
        </div>
        <div class="bottom-line">
          <span class="bottom-line--copy">Copyright &copy; 2019</span>
          <div class="bottom-line--icons">
            <a href="#" class="btn btn--small"><img src="{% static 'images/icon-facebook.svg' %}"/></a>
            <a href="#" class="btn btn--small"><img src="{% static 'images/icon-instagram.svg' %}"/></a>
          </div>
        </div>
      </footer>

      <script src="{% static 'js/app.js' %}"></script>
</body>
</html>

oddam_w_dobre_rece/charity/templates/form-confirmation.html
{% extends "base.html" %}
{% block content %}

<div id="form-confirmation" class="slogan container container--90">
  <h2>
    Dziękujemy za przesłanie formularza. Na maila prześlemy wszelkie
    informacje o odbiorze.
  </h2>
</div>

{% endblock content %}

oddam_w_dobre_rece/charity/templates/form.html
{% extends 'base.html' %}
{% load static %}
{% block content %}
<div id="form-section">
    <section class="form--steps">
      <div class="form--steps-instructions">
        <div class="form--steps-container">
          <h3>Ważne!</h3>
          <p data-step="1" class="active">
            Uzupełnij szczegóły dotyczące Twoich rzeczy. Dzięki temu będziemy
            wiedzieć komu najlepiej je przekazać.
          </p>
          <p data-step="2">
            Uzupełnij szczegóły dotyczące Twoich rzeczy. Dzięki temu będziemy
            wiedzieć komu najlepiej je przekazać.
          </p>
          <p data-step="3">
           Wybierz jedną, do
            której trafi Twoja przesyłka.
          </p>
          <p data-step="4">Podaj adres oraz termin odbioru rzeczy.</p>
        </div>
      </div>

      <div class="form--steps-container">
        <div class="form--steps-counter">Krok <span>1</span>/5</div>

         <form id="donation-form" action="/add-donation/" method="post">
          {% csrf_token %}
          <!-- STEP 1: class .active is switching steps -->
          <div data-step="1" class="active">
            <h3>Zaznacz co chcesz oddać:</h3>
            <div id="category-checkbox">
            <input type="hidden" id="checked-categories" name="chosen-categories"/>


            {% for category in categories %}
            <div class="form-group form-group--checkbox">
              <label>

                <input
                  type="checkbox"
                  name="categories"
                  value="{{ category.id }}"
                  data-name="{{ category.name }}"
                />

                <span class="checkbox"></span>
                <span class="description">{{ category.name }}</span>
              </label>
            </div>
            {% endfor %}
              </div>


            <div class="form-group form-group--buttons">
              <button type="button" class="btn next-step">Dalej</button>
            </div>
          </div>

          <!-- STEP 2 -->
          <div data-step="2">
            <h3>Podaj liczbę 60l worków, w które spakowałeś/aś rzeczy:</h3>

            <div class="form-group form-group--inline">
              <label>
                Liczba 60l worków:
                <input type="number" id="bags" name="quantity" step="1" min="1" />
              </label>
            </div>

            <div class="form-group form-group--buttons">
              <button type="button" class="btn prev-step">Wstecz</button>
              <button type="button" class="btn next-step">Dalej</button>
            </div>
          </div>



          <!-- STEP 3 -->
          <div data-step="3">
            <h3>Wybierz organizacje, której chcesz pomóc:</h3>
            <div id="institution-checkbox">
            {% for institution in institutions %}
            <div class="form-group form-group--checkbox">
              <label>
                <input type="radio" name="institution" value="{{institution.id}}" />
                <span class="checkbox radio"></span>
                <span class="description">
                  <div class="title">{{institution.name}}</div>
                  <div class="subtitle">
                    {{institution.description}}
                  </div>
                </span>
                <categories>
                {% if institution.categories %}
                {% for category in institution.categories.all %}
                <input type="hidden" value="{{category.id}}"/>
                {% endfor %}
                {% endif %}
                </categories>

              </label>
            </div>
            {% endfor %}
            </div>

            <div class="form-group form-group--buttons">
              <button type="button" class="btn prev-step">Wstecz</button>
              <button type="button" class="btn next-step">Dalej</button>
            </div>
          </div>

          <!-- STEP 4 -->
          <div data-step="4">
            <h3>Podaj adres oraz termin odbioru rzecz przez kuriera:</h3>

            <div class="form-section form-section--columns">
              <div class="form-section--column">
                <h4>Adres odbioru</h4>
                <div class="form-group form-group--inline">
                  <label> Ulica <input type="text" name="address" /> </label>
                </div>

                <div class="form-group form-group--inline">
                  <label> Miasto <input type="text" name="city" /> </label>
                </div>

                <div class="form-group form-group--inline">
                  <label>
                    Kod pocztowy <input type="text" name="zip_code" />
                  </label>
                </div>

                <div class="form-group form-group--inline">
                  <label>
                    Numer telefonu <input type="phone" name="phone_number" />
                  </label>
                </div>
              </div>

              <div class="form-section--column">
                <h4>Termin odbioru</h4>
                <div class="form-group form-group--inline">
                  <label> Data <input type="date" name="pick_up_date" /> </label>
                </div>

                <div class="form-group form-group--inline">
                  <label> Godzina <input type="time" name="pick_up_time" /> </label>
                </div>

                <div class="form-group form-group--inline">
                  <label>
                    Uwagi dla kuriera
                    <textarea name="more_info" rows="5" value=""></textarea>
                  </label>
                </div>
              </div>
            </div>
            <div class="form-group form-group--buttons">
              <button type="button" class="btn prev-step">Wstecz</button>
              <button id="summary-button" type="button" class="btn next-step">Dalej</button>
            </div>
          </div>

          <!-- STEP 5 -->
          <div data-step="5">
            <h3>Podsumowanie Twojej darowizny</h3>

            <div class="summary">
              <div class="form-section">
                <h4>Oddajesz:</h4>
                <ul>
                  <li>
                    <span class="icon icon-bag"></span>
                    <span class="summary--text"
                      >4 worki ubrań w dobrym stanie dla dzieci</span
                    >
                  </li>

                  <li>
                    <span class="icon icon-hand"></span>
                    <span class="summary--text"
                      >Dla fundacji "Mam marzenie" w Warszawie</span
                    >
                  </li>
                </ul>
              </div>

              <div class="form-section form-section--columns">
                <div class="form-section--column">
                  <h4>Adres odbioru:</h4>
                  <ul>
                    <li>Prosta 51</li>
                    <li>Warszawa</li>
                    <li>99-098</li>
                    <li>123 456 789</li>
                  </ul>
                </div>

                <div class="form-section--column">
                  <h4>Termin odbioru:</h4>
                  <ul>
                    <li>13/12/2018</li>
                    <li>15:40</li>
                    <li>Brak uwag</li>
                  </ul>
                </div>
              </div>
            </div>

            <div class="form-group form-group--buttons">
              <button type="button" class="btn prev-step">Wstecz</button>
              <button type="submit" class="btn">Potwierdzam</button>
            </div>
          </div>
        </form>
      </div>
    </section>
  </div>
{% endblock content %}

oddam_w_dobre_rece/charity/templates/index.html
{% extends 'base.html' %}
{% load static %}
{% block content %}
    <section id="stats" class="stats">
      <div class="container container--85">
        <div class="stats--item">
          <em>{{ sum_of_bags }}</em>
          <h3>Oddanych worków</h3>
          <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Eius est beatae, quod accusamus illum tempora!</p>
        </div>

        <div class="stats--item">
          <em>{{ institutions_count }}</em>
          <h3>Wspartych organizacji</h3>
          <p>Lorem ipsum dolor sit amet consectetur, adipisicing elit. Laboriosam magnam, sint nihil cupiditate quas quam.</p>
        </div>

      </div>
    </section>

    <section id="steps" class="steps">
      <h2>Wystarczą 4 proste kroki</h2>

      <div class="steps--container">
        <div class="steps--item">
          <span class="icon icon--hands"></span>
          <h3>Wybierz rzeczy</h3>
          <p>ubrania, zabawki, sprzęt i inne</p>
        </div>
        <div class="steps--item">
          <span class="icon icon--arrow"></span>
          <h3>Spakuj je</h3>
          <p>skorzystaj z worków na śmieci</p>
        </div>
        <div class="steps--item">
          <span class="icon icon--glasses"></span>
          <h3>Zdecyduj komu chcesz pomóc</h3>
          <p>wybierz zaufane miejsce</p>
        </div>
        <div class="steps--item">
          <span class="icon icon--courier"></span>
          <h3>Zamów kuriera</h3>
          <p>kurier przyjedzie w dogodnym terminie</p>
        </div>
      </div>

      <a href="/register/#register-section" class="btn btn--large">Załóż konto</a>
    </section>

    <section id="about-us" class="about-us">
      <div class="about-us--text">
        <h2>O nas</h2>
        <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Voluptas vitae animi rem pariatur incidunt libero optio esse quisquam illo omnis.</p>
        <img src="{% static 'images/signature.svg' %}" class="about-us--text-signature" alt="Signature" />
      </div>
      <div class="about-us--image"><img src="{% static 'images/about-us.jpg' %}" alt="People in circle" /></div>
    </section>

     <section id="help" class="help">
      <h2>Komu pomagamy?</h2>

      <ul class="help--buttons">
        <li data-id="1"><a href="#" class="btn btn--without-border active">Fundacjom</a></li>
        <li data-id="2"><a href="#" class="btn btn--without-border">Organizacjom pozarządowym</a></li>
        <li data-id="3"><a href="#" class="btn btn--without-border">Lokalnym zbiórkom</a></li>
      </ul>

      <!-- SLIDE 1 -->
      <div class="help--slides active" data-id="1">
        <p>W naszej bazie znajdziesz listę zweryfikowanych Fundacji, z którymi współpracujemy. Możesz sprawdzić czym się zajmują, komu pomagają i czego potrzebują.</p>
        {% for institution in institutions %}
        {% if institution.type == "FU" %}
        <ul class="help--slides-items">
          <li>
            <div class="col">
              <div class="title">{{ institution.name }}</div>
              <div class="subtitle">{{ institution.description }}</div>
            </div>

            <div class="col"><div class="text">{{ institution.categories.all|join:", " }}</div></div>
          </li>
        </ul>
        {% endif %}
        {% endfor %}
        <!-- Pagination
        <ul class="help--slides-pagination">
          <li><a href="#" class="btn btn--small btn--without-border active" data-page="1">1</a></li>
          <li><a href="#" class="btn btn--small btn--without-border" data-page="2">2</a></li>
          <li><a href="#" class="btn btn--small btn--without-border" data-page="3">3</a></li>
        </ul>
        -->
      </div>


      <!-- SLIDE 2 -->
      <div class="help--slides" data-id="2">
        <p>
          Lorem ipsum dolor, sit amet consectetur adipisicing elit. Hic officiis mollitia dolor, neque aspernatur accusamus debitis. Ducimus, officia. Quia, sunt illum! Non iste placeat ab ipsum alias
          quos suscipit corporis!
        </p>
        {% for institution in institutions %}
        {% if institution.type == "OP" %}
        <ul class="help--slides-items">
          <li>
            <div class="col">
              <div class="title">{{ institution.name }}</div>
              <div class="subtitle">{{ institution.description }}</div>
            </div>

            <div class="col"><div class="text">{{ institution.categories.all|join:", " }}</div></div>
          </li>
        </ul>
        {% endif %}
        {% endfor %}

        <!-- Pagination
        <ul class="help--slides-pagination">
          <li><a href="#" class="btn btn--small btn--without-border active" data-page="1">1</a></li>
          <li><a href="#" class="btn btn--small btn--without-border" data-page="2">2</a></li>
          <li><a href="#" class="btn btn--small btn--without-border" data-page="3">3</a></li>
          <li><a href="#" class="btn btn--small btn--without-border" data-page="4">4</a></li>
          <li><a href="#" class="btn btn--small btn--without-border" data-page="5">5</a></li>
        </ul>
        -->
      </div>

      <!-- SLIDE 3 -->
      <div class="help--slides" data-id="3">
        <p>Lorem ipsum dolor sit amet, his ocurreret persequeris ea, ad utinam laudem duo. Verterem adipisci partiendo eos ne, ea his reque quaeque recteque, ne quo lobortis intellegam.</p>
        {% for institution in institutions %}
        {% if institution.type == "ZO" %}
        <ul class="help--slides-items">
          <li>
            <div class="col">
              <div class="title">{{ institution.name }}</div>
              <div class="subtitle">{{ institution.description }}</div>
            </div>

            <div class="col"><div class="text">{{ institution.categories.all|join:", " }}</div></div>
          </li>
        </ul>
        {% endif %}
        {% endfor %}
        <!-- Pagination
        <ul class="help--slides-pagination">
          <li><a href="#" class="btn btn--small btn--without-border active" data-page="1">1</a></li>
          <li><a href="#" class="btn btn--small btn--without-border" data-page="2">2</a></li>
        </ul>
        -->
      </div>
    </section>
{% endblock content %}

oddam_w_dobre_rece/charity/templates/login.html
{% load static %}
<!DOCTYPE html>
  <html lang="pl">
    <head>
      <meta charset="UTF-8" />
      <meta name="viewport" content="width=device-width, initial-scale=1.0" />
      <meta http-equiv="X-UA-Compatible" content="ie=edge" />
      <title>Document</title>
      <link rel="stylesheet" href="{% static 'css/style.css' %}" />
    </head>
    <body>
      <header class="header--main-page">
        <nav class="container container--70">
          <ul class="nav--actions">
            {% if user.is_authenticated %}
              <li class="logged-user">
                Witaj {{ user.first_name }}
                <ul class="dropdown">
                  <li><a href="/profile#user-profile">Profil</a></li>
                  <li><a href="#">Ustawienia</a></li>
                  {% if user.is_superuser %}
                  <li><a href="/admin">Panel administratora</a></li>
                  {% endif %}
                  <li><a href="/logout">Wyloguj</a></li>
                </ul>
              </li>
            {% else %}
              <li><a href="/login/#login-section" class="btn btn--small btn--without-border">Zaloguj</a></li>
              <li><a href="/register/#register-section" class="btn btn--small btn--highlighted">Załóż konto</a></li>
            {% endif %}
          </ul>

          <ul>
            <li><a href="/" class="btn btn--without-border active">Start</a></li>
            <li><a href="#steps" class="btn btn--without-border">O co chodzi?</a></li>
            <li><a href="#about-us" class="btn btn--without-border">O nas</a></li>
            <li><a href="#help" class="btn btn--without-border">Fundacje i organizacje</a></li>
            <li><a href="/add-donation/#form-steps" class="btn btn--without-border">Przekaż dary</a></li>
            <li><a href="#contact" class="btn btn--without-border">Kontakt</a></li>
          </ul>
        </nav>

    <div id="login-section">
        <section class="login-page">
          <h2>Zaloguj się</h2>
          <form method="post" action="">
            {% csrf_token %}

            {% for field in form %}
            <div class="form-group">
                {{ field }}
                {% for error in field.errors %}
              <p style="color: red">{{ error }}</p>
            {% endfor %}
            {% if error %}
              <p style="color: red">{{ error }}</p>
            {% endif %}
            </div>
            {% endfor %}

            <div class="form-group form-group--buttons">
              <a href="/register/#register-section" class="btn btn--without-border">Załóż konto</a>
              <button class="btn" type="submit">Zaloguj się</button>
            </div>
          </form>
        </section>
    </div>

      <footer>
        <div id="contact" class="contact">
          <h2>Skontaktuj się z nami</h2>
          <h3>Formularz kontaktowy</h3>
          <form class="form--contact">
            <div class="form-group form-group--50"><input type="text" name="name" placeholder="Imię" /></div>
            <div class="form-group form-group--50"><input type="text" name="surname" placeholder="Nazwisko" /></div>

            <div class="form-group"><textarea name="message" placeholder="Wiadomość" rows="1"></textarea></div>

            <button class="btn" type="submit">Wyślij</button>
          </form>
        </div>
        <div class="bottom-line">
          <span class="bottom-line--copy">Copyright &copy; 2019</span>
          <div class="bottom-line--icons">
            <a href="#" class="btn btn--small"><img src="{% static 'images/icon-facebook.svg' %}"/></a>
            <a href="#" class="btn btn--small"><img src="{% static 'images/icon-instagram.svg' %}"/></a>
          </div>
        </div>
      </footer>

      <script src="{% static 'js/app.js' %}"></script>
    </body>
  </html>

oddam_w_dobre_rece/charity/templates/register.html
{% extends 'base.html' %}
{% block content %}
<div id="register-section">
    <section class="login-page">
      <h2>Załóż konto</h2>

      <form action="", method="post">
        {% csrf_token %}
        {% for field in form %}
        <div class="form-group">
            {{ field }}
            {% for error in field.errors %}
          <p style="color: red">{{ error }}</p>
        {% endfor %}
        </div>
        {% endfor %}

        <div class="form-group form-group--buttons">
          <a href="login.html" class="btn btn--without-border">Zaloguj się</a>
          <button class="btn" type="submit">Załóż konto</button>
        </div>
      </form>
    </section>
</div>
{% endblock content %}

oddam_w_dobre_rece/charity/templates/user-profile.html
{% extends "base.html" %}
{% block content %}
{% load static %}

    <section id="user-profile">
      <div class="container container--90">
          <h2>
            Profil użytkownika
          </h2>
        <h2>Imię: {{user.first_name}}</h2>
        <h2>Nazwisko: {{user.last_name}}</h2>
        <h2>Email: {{user.email}}</h2>
          <h2>Przekazane dary:</h2>
          <ul>
          {% for donation in user.donation_set.all %}
              <li>
          <p style="font-size: 20px"><b>{{donation.quantity}}</b> worków zawierających
                    {% for category in donation.categories.all %}<b>{{category}}, </b>{% endfor %}
              dla organizacji <b>{{donation.institution.name}}</b>. Data odbioru worków: <b>{{donation.pick_up_date}}</b></p></li>
          {% endfor %}
          </ul>
      </div>
    </section>
{% endblock content %}